micronaut:
  server:
    port: 9000

airbyte:
  config-dir: /config
#  config-dir: /Users/cole/data/con-orc
#  local:
#    docker-mount: ${LOCAL_DOCKER_MOUNT:}
#    root: ${LOCAL_ROOT:}
#  worker:
#    job:
#      kube:
#        namespace: ${JOB_KUBE_NAMESPACE:default}
#  workspace:
#    docker-mount: ${WORKSPACE_DOCKER_MOUNT:}
#    root: ${WORKSPACE_ROOT:}

#docker:
#  network: ${DOCKER_NETWORK:host}