apiVersion: v1
kind: Pod
metadata:
  generateName: run-source-harness
  labels:
    app: source-harness
spec:
  containers:
  - name: main
    image: airbyte/source-harness:dev
    args: ["airbyte/source-postgres:dev"]
    volumeMounts:
      - name: secrets-volume
        mountPath: /airbyte/secrets
    resources:
      limits:
        cpu: "2.5"
        memory: "2Gi"
      requests:
        cpu: "2.5"
        memory: "2Gi"
  volumes:
    - name: secrets-volume
      hostPath:
        path: ./airbyte-integrations/connectors/source-harness/secrets
        type: Directory
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never
