apiVersion: v1
kind: Pod
metadata:
  generateName: run-source-harness
  labels:
    app: source-harness
spec:
  containers:
  - name: main
    image: airbyte/source-harness:dev
    args: ["airbyte/source-postgres:dev"]
  resources:
    limits:
      cpu: "2.5"
      memory: "2Gi"
    requests:
      cpu: "2.5"
      memory: "2Gi"
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never
