acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: satisfaction_ratings
          - name: tickets
          - name: time_entries
          - name: conversations
          - name: scenario_automations
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.3.4
        config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  spec:
    tests:
      - spec_path: source_freshdesk/spec.json
connector_image: airbyte/source-freshdesk:dev
test_strictness_level: high
