# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-freshdesk:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_freshdesk/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
      # please remove the backward_capability checks bypass, once updated to the newer version
        backward_compatibility_tests_config:
          disable_for_version: "0.3.4"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        empty_streams:
          - name: satisfaction_ratings
            bypass_reason: "no records"
          - name: tickets
            bypass_reason: "no records"
          - name: time_entries
            bypass_reason: "no records"
          - name: conversations
            bypass_reason: "no records"
          - name: scenario_automations
            bypass_reason: "no records"
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
