acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        expect_records:
          path: integration_tests/expected_records.txt
      - config_path: secrets/config_users_only.json
        empty_streams:
          - name: applications
          - name: applications_demographics_answers
          - name: applications_interviews
          - name: candidates
          - name: close_reasons
          - name: custom_fields
          - name: degrees
          - name: demographics_answers
          - name: demographics_answer_options
          - name: questions
          - name: demographics_answers_answer_options
          - name: demographics_question_sets
          - name: demographics_question_sets_questions
          - name: departments
          - name: jobs
          - name: jobs_openings
          - name: interviews
          - name: job_posts
          - name: job_stages
          - name: jobs_stages
          - name: offers
          - name: rejection_reasons
          - name: scorecards
          - name: sources
          - name: demographics_questions
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/config_invalid.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
      - config_path: secrets/config_users_only.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
      - config_path: secrets/config_users_only.json
        configured_catalog_path: integration_tests/configured_catalog_users_only.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/incremental_configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  spec:
    tests:
      - spec_path: source_greenhouse/spec.json
connector_image: airbyte/source-greenhouse:dev
test_strictness_level: high
