---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/StagingConfiguration.yaml
title: ActorConfigurationBinding
description: The class represents the extra information required by an actor for other purposes such as mutation in cloud
type: object
required:
  - actorDefinitionId
additionalProperties: false
properties:
  actorDefinitionId:
    type: string
    format: uuid
  configuration:
    description: Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
