connector_image: airbyte/source-breaker:dev
test_strictness_level: high
acceptance_tests:
  connection:
    tests:
      - config_path: test_configs/config.json
        status: succeed
      - config_path: test_configs/config_check_connection_fail.json
        status: failed
      - config_path: test_configs/config_check_job_fail.json
        status: exception
  spec:
    tests:
      - spec_path: source_breaker/spec.json
  discovery:
    tests:
      - config_path: test_configs/config.json
  basic_read:
    tests:
      - config_path: test_configs/config.json
        empty_streams: []
        expect_records:
          path: integration_tests/expected_records.jsonl
          exact_order: true
          extra_fields: false
          extra_records: false
  full_refresh:
    tests:
      - config_path: test_configs/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        ignored_fields:
          users:
            - created_at
            - updated_at
  incremental:
    tests:
      - config_path: test_configs/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
