acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: alerts
        expect_records:
          path: integration_tests/expected_records.txt
        timeout_seconds: 600
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/constant_records_catalog.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/no_empty_streams_no_usage_records_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
      - config_path: secrets/config_with_lookback.json
        configured_catalog_path: integration_tests/no_empty_streams_no_usage_records_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        threshold_days: 30
  spec:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.10
        spec_path: source_twilio/spec.json
connector_image: airbyte/source-twilio:dev
test_strictness_level: high
