connector_image: airbyte/source-amplitude:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_amplitude/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    bypass_reason: "
      There is the `Events` stream which generates millions of thousands records/hour, 
      and was removed previously from `configured_catalog`, because it takes more than 10 hours just to sync a single day.
      This test is skipped because we should have a workaround for SAT to bypass such large and heavy streams or provide the custom catalog instead.
      "
  incremental: 
    tests:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog_without_events.json"
      future_state:
        bypass_reason: "Unable to use 'state_path' because Amplitude returns an error when specifying a date in the future."
  full_refresh:
    tests:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog_without_events.json"
