acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog_without_events.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog_without_events.json
  spec:
    tests:
      - spec_path: source_amplitude/spec.json
connector_image: airbyte/source-amplitude:dev
test_strictness_level: high
