micronaut:
  application:
    name: airbyteApiServer
  http:
    services:
      config-api:
        url: "http://localhost:8000"
        read-timeout: 1m
netty:
  default:
    allocator:
      max-order: 3

airbyte:
  configServerUrl: "localhost:8080"
