# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-stripe-alex:dev
tests:
  spec:
    - spec_path: "source_stripe_alex/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"