connector_image: airbyte/source-stripe-alex:dev
tests:
  spec:
    - spec_path: "source_stripe_alex/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/full_refresh_configured_catalog.json"
      timeout_seconds: 3600
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/invoice_and_invoice_items_catalog.json"
      future_state_path: "integration_tests/abnormal_state.json"
      timeout_seconds: 3600
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/full_refresh_configured_catalog.json"
      timeout_seconds: 3600
      ignored_fields:
        "invoices":
          - invoice_pdf
          - hosted_invoice_url
