acceptance_tests:
  basic_read:
    tests:
      - config_path: integration_tests/config.json
  connection:
    tests:
      - config_path: integration_tests/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: integration_tests/config.json
  full_refresh:
    tests:
      - config_path: integration_tests/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  spec:
    tests:
      - spec_path: source_file/spec.json
connector_image: airbyte/source-file:dev
test_strictness_level: high
