acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        timeout_seconds: 1800
      - config_path: secrets/config_oauth.json
        timeout_seconds: 1800
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
        timeout_seconds: 180
      - config_path: secrets/config_apikey.json
        status: succeed
        timeout_seconds: 180
      - config_path: secrets/config_oauth.json
        status: succeed
        timeout_seconds: 180
      - config_path: integration_tests/invalid_config.json
        status: failed
        timeout_seconds: 180
      - config_path: integration_tests/invalid_config_apikey.json
        status: failed
        timeout_seconds: 180
      - config_path: integration_tests/invalid_config_oauth.json
        status: failed
        timeout_seconds: 180
  discovery:
    tests:
      - config_path: secrets/config.json
      - config_path: secrets/config_apikey.json
      - config_path: secrets/config_oauth.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog_without_email_activities.json
        timeout_seconds: 1800
      - config_path: secrets/config_oauth.json
        configured_catalog_path: integration_tests/configured_catalog_without_email_activities.json
        timeout_seconds: 1800
  spec:
    tests:
      - spec_path: source_mailchimp/spec.json
        timeout_seconds: 60
connector_image: airbyte/source-mailchimp:dev
test_strictness_level: high
