acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: external_account_bank_accounts
      - config_path: secrets/config.json
        timeout_seconds: 3600
      - config_path: secrets/connected_account_config.json
        timeout_seconds: 3600
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/connected_account_config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.37
        config_path: secrets/config.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.37
        config_path: secrets/connected_account_config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/non_invoice_line_items_catalog.json
        timeout_seconds: 3600
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/full_refresh_configured_catalog.json
      - config_path: secrets/connected_account_config.json
        configured_catalog_path: integration_tests/connected_account_configured_catalog.json
        ignored_fields:
          invoices:
            - invoice_pdf
            - hosted_invoice_url
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/non_invoice_line_items_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
      - config_path: secrets/connected_account_config.json
        configured_catalog_path: integration_tests/connected_account_configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  spec:
    tests:
      - spec_path: source_stripe/spec.yaml
connector_image: airbyte/source-stripe:dev
test_strictness_level: high
