# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-pokeapi:dev
tests:
  connection:
    - config_path: "integration_tests/config.json"
      status: "succeed"
  discovery:
    - config_path: "integration_tests/config.json"
      backward_compatibility_tests_config:
        # this change is technically breaking because it removes the `null` types.
        disable_for_version: "0.1.5"
  basic_read:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
  full_refresh:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
