acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/prod_config.json
        timeout_seconds: 1200
      - config_path: secrets/prod_config.json
        timeout_seconds: 1200
      - config_path: secrets/prod_config.json
        timeout_seconds: 1200
      - config_path: secrets/prod_config_with_day_granularity.json
        timeout_seconds: 1200
      - config_path: secrets/prod_config_with_lifetime_granularity.json
        timeout_seconds: 1200
  connection:
    tests:
      - config_path: secrets/prod_config.json
        status: succeed
      - config_path: secrets/prod_config_with_day_granularity.json
        status: succeed
      - config_path: secrets/prod_config_with_lifetime_granularity.json
        status: succeed
      - config_path: secrets/new_config_prod.json
        status: succeed
      - config_path: secrets/config_oauth.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
      - config_path: integration_tests/invalid_config_access_token.json
        status: failed
      - config_path: integration_tests/invalid_config_oauth.json
        status: failed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.14
        config_path: secrets/prod_config.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.14
        config_path: secrets/prod_config_with_day_granularity.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.14
        config_path: secrets/prod_config_with_lifetime_granularity.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.14
        config_path: secrets/config.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.14
        config_path: secrets/new_config_prod.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.14
        config_path: secrets/config_oauth.json
  full_refresh:
    tests:
      - config_path: secrets/prod_config.json
        configured_catalog_path: integration_tests/streams_basic.json
        ignored_fields:
          ad_groups:
            - dayparting
            - enable_search_result
            - display_mode
            - schedule_infos
            - feed_type
            - status
        timeout_seconds: 7200
      - config_path: secrets/prod_config.json
        configured_catalog_path: integration_tests/streams_reports_daily.json
        timeout_seconds: 7200
      - config_path: secrets/prod_config.json
        configured_catalog_path: integration_tests/streams_reports_lifetime.json
        timeout_seconds: 7200
  incremental:
    tests:
      - config_path: secrets/prod_config.json
        configured_catalog_path: integration_tests/streams_basic.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 7200
      - config_path: secrets/prod_config.json
        configured_catalog_path: integration_tests/streams_reports_daily.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 7200
  spec:
    tests:
      - spec_path: integration_tests/spec.json
connector_image: airbyte/source-tiktok-marketing:dev
test_strictness_level: high
