# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-postgres:1.0.43
acceptance_tests:
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/incremental_configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
      # - config_path: "secrets/config_cdc.json"
      #   configured_catalog_path: "integration_tests/incremental_configured_catalog.json"
      #   future_state:
      #     future_state_path: "integration_tests/abnormal_state.json"
