# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-postgres:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "src/test-integration/resources/expected_spec.json"
        config_path: "src/test-integration/resources/dummy_config.json"
        timeout_seconds: 60
  connection:
    tests:
      - config_path: "secrets/credentials.json"
        status: "succeed"
        timeout_seconds: 60
  discovery:
    tests:
      - config_path: "secrets/credentials.json"
        timeout_seconds: 60
  basic_read:
    tests:
      - config_path: "secrets/credentials.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        timeout_seconds: 180
  full_refresh:
    tests:
      - config_path: "secrets/credentials.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        timeout_seconds: 180