# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-postgres:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "src/test-integration/resources/expected_spec.json"
        config_path: "secrets/config.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.txt"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
  incremental:
    bypass_reason: "The test database is not yet seeded with an incremental stream."