acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config_oauth.json
  connection:
    tests:
      - config_path: secrets/config_oauth.json
        status: succeed
        timeout_seconds: 60
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config_oauth.json
        timeout_seconds: 60
  full_refresh:
    tests:
      - config_path: secrets/config_oauth.json
        configured_catalog_path: integration_tests/configured_catalog.json
  incremental:
    tests:
      - config_path: secrets/config_oauth.json
        configured_catalog_path: integration_tests/configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  spec:
    tests:
      - spec_path: source_linkedin_ads/spec.json
connector_image: airbyte/source-linkedin-ads:dev
test_strictness_level: high
