acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
      - config_path: secrets/config.json
      - config_path: secrets/config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
        timeout_seconds: 60
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
        timeout_seconds: 60
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/catalog_lifetime.json
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/catalog_daily.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/catalog_daily.json
  spec:
    tests:
      - spec_path: source_snapchat_marketing/spec.json
connector_image: airbyte/source-snapchat-marketing:dev
test_strictness_level: high
