acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: order
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.12
        config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/product_catalog_v2_configured_catalog.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/product_catalog_v2_configured_catalog.json
        cursor_paths:
          attached_item:
            - cbdemo_standard
            - updated_at
        future_state:
          future_state_path: integration_tests/future_state.json
  spec:
    tests:
      - spec_path: source_chargebee/spec.json
connector_image: airbyte/source-chargebee:dev
test_strictness_level: high
