acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: account_performance_report_hourly
          - name: ad_group_performance_report_hourly
          - name: ad_performance_report_hourly
          - name: campaign_performance_report_hourly
          - name: keyword_performance_report_hourly
  connection:
    tests:
      - config_path: secrets/config_old.json
        status: succeed
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  spec:
    tests:
      - spec_path: source_bing_ads/spec.json
connector_image: airbyte/source-bing-ads:dev
test_strictness_level: high
