acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/old_config.json
        status: succeed
      - config_path: secrets/config_oauth.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        cursor_paths:
          contacts:
            - updated_at
          expenses_clients:
            - to
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 2400
  spec:
    tests:
      - spec_path: source_harvest/spec.json
connector_image: airbyte/source-harvest:dev
test_strictness_level: high
