acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: lists
          - name: campaigns
        expect_records:
          path: integration_tests/expected_records.txt
        timeout_seconds: 3600
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        timeout_seconds: 3600
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/incremental_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 3600
  spec:
    tests:
      - spec_path: source_marketo/spec.json
connector_image: airbyte/source-marketo:dev
test_strictness_level: high
