acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: ad_account_analytics
          - name: ad_accounts
          - name: ad_analytics
          - name: ad_group_analytics
          - name: ad_groups
          - name: ads
          - name: board_pins
          - name: board_section_pins
          - name: board_sections
          - name: boards
          - name: campaign_analytics
          - name: campaigns
          - name: user_account_analytics
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
      - config_path: secrets/config_oauth.json
        status: succeed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.2
        config_path: secrets/config.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.2
        config_path: secrets/config_oauth.json
  spec:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.2
        spec_path: source_pinterest/spec.json
connector_image: airbyte/source-pinterest:dev
test_strictness_level: high
