# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-stock-ticker-api-cdk:dev
tests:
  spec:
    - spec_path: "source_stock_ticker_api_cdk/spec.json"
  connection:
    - config_path: "integration_tests/sample_config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "integration_tests/sample_config.json"
  basic_read:
    - config_path: "integration_tests/sample_config.json"
      configured_catalog_path: "integration_tests/configured_catalog_fullrefresh.json"
      empty_streams: []
  incremental:
    - config_path: "integration_tests/sample_config.json"
      configured_catalog_path: "integration_tests/configured_catalog_incremental.json"
      future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    - config_path: "integration_tests/sample_config.json"
      configured_catalog_path: "integration_tests/configured_catalog_fullrefresh.json"
