acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/service_config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/config_with_url.json
        status: succeed
      - config_path: secrets/service_config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: exception
  discovery:
    tests:
      - config_path: secrets/service_config.json
  full_refresh:
    tests:
      - config_path: secrets/service_config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  spec:
    tests:
      - spec_path: google_sheets_source/spec.yaml
connector_image: airbyte/source-google-sheets:dev
test_strictness_level: high
