acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams: []
        timeout_seconds: 1800
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/service_account_config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/catalog.json
        timeout_seconds: 1800
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog_incremental.json
        cursor_paths:
          custom_dimensions:
            - https://airbyte.io
            - web
            - date
          search_analytics_all_fields:
            - https://airbyte.io
            - web
            - date
          search_analytics_by_country:
            - https://airbyte.io
            - web
            - image
          search_analytics_by_device:
            - https://airbyte.io
            - web
            - date
          search_analytics_by_page:
            - https://airbyte.io
            - web
            - date
          search_analytics_by_query:
            - https://airbyte.io
            - web
            - date
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
  spec:
    tests:
      - spec_path: source_google_search_console/spec.json
connector_image: airbyte/source-google-search-console:dev
test_strictness_level: high
