# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-google-search-console:dev
test_strictness_level: "high"
acceptance_tests:
  spec:
    tests:
      - spec_path: "integration_tests/spec.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.1.20" # custom_reports format changed to list
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "secrets/service_account_config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.1.20" # custom_reports format changed to list
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          extra_fields: yes
          exact_order: yes
          extra_records: no
        timeout_seconds: 1800
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/catalog.json"
        timeout_seconds: 1800
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog_incremental.json"
        timeout_seconds: 1800
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
        cursor_paths:
          search_analytics_by_country: [ "https://airbyte.io", "web", "image" ]
          search_analytics_by_device: [ "https://airbyte.io", "web", "date" ]
          search_analytics_by_page: [ "https://airbyte.io", "web", "date" ]
          search_analytics_by_query: [ "https://airbyte.io", "web", "date" ]
          search_analytics_all_fields: [ "https://airbyte.io", "web", "date" ]
          custom_dimensions: [ "https://airbyte.io", "web", "date" ]
