acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: form_submissions
          - name: ticket_pipelines
          - name: engagements_meetings
          - name: engagements_emails
          - name: engagements
          - name: engagements_calls
          - name: quotes
        timeout_seconds: 600
      - config_path: secrets/config_oauth.json
        empty_streams:
          - name: form_submissions
          - name: ticket_pipelines
          - name: engagements_meetings
          - name: engagements_emails
          - name: engagements
          - name: engagements_calls
          - name: quotes
        timeout_seconds: 600
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/config_oauth.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
      - config_path: integration_tests/invalid_config_oauth.json
        status: failed
      - config_path: integration_tests/invalid_config_wrong_title.json
        status: failed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.83
        config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: sample_files/full_refresh_catalog.json
        ignored_fields:
          companies:
            - properties
            - hs_time_in_subscriber
          contact_lists:
            - properties
            - ilsFilterBranch
          contacts:
            - properties
            - hs_time_in_subscriber
          deals:
            - properties
            - hs_time_in_qualifiedtobuy
          tickets:
            - properties
            - hs_time_in_4
      - config_path: secrets/config_oauth.json
        configured_catalog_path: sample_files/full_refresh_oauth_catalog.json
        ignored_fields:
          companies:
            - properties
            - hs_time_in_subscriber
          contact_lists:
            - properties
            - ilsFilterBranch
          contacts:
            - properties
            - hs_time_in_subscriber
          deals:
            - properties
            - hs_time_in_qualifiedtobuy
          tickets:
            - properties
            - hs_time_in_4
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: sample_files/incremental_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  spec:
    tests:
      - spec_path: source_hubspot/spec.yaml
connector_image: airbyte/source-hubspot:dev
test_strictness_level: high
