---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/ConnectorBuilderProject.yaml
title: ActorDefinitionConfigInjection
description: JSON object that is injected into every run of the referenced actor definition
type: object
required:
  - actorDefinitionConfigInjectionId
  - actorDefinitionId
  - jsonToInject
  - injectionPath
additionalProperties: false
properties:
  actorDefinitionConfigInjectionId:
    type: string
    format: uuid
  injectionPath:
    type: string
  actorDefinitionId:
    type: string
    format: uuid
  jsonToInject:
    description: Integration specific blob. Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
