---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/JobConnectorBuilderReadConfig.yaml
title: JobConnectorBuilderReadConfig
description: job connector builder read config
type: object
additionalProperties: false
required:
  - dockerImage
properties:
  dockerImage:
    type: string
    description: The connector image
    example: airbyte/source-postgres:1.0.12
