acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
      - config_path: secrets/config_oauth.json
  connection:
    tests:
      - config_path: secrets/config_old.json
        status: succeed
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/config_oauth.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config_old.json
      - config_path: secrets/config.json
      - config_path: secrets/config_oauth.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        cursor_paths:
          agent_timeline:
            - start_time
          agents:
            - id
          bans:
            - id
          chats:
            - update_timestamp
  spec:
    tests:
      - spec_path: source_zendesk_chat/spec.json
connector_image: airbyte/source-zendesk-chat:dev
test_strictness_level: high
