acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
      - config_path: secrets/config_old.json
        status: succeed
  discovery:
    tests:
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.3
        config_path: secrets/config.json
      - backward_compatibility_tests_config:
          disable_for_version: 0.1.3
        config_path: secrets/config_old.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        ignored_fields:
          account_overview:
            - current_timestamp
          agents_overview:
            - current_timestamp
          current_queue_activity:
            - current_timestamp
  incremental:
    tests:
      - config_path: secrets/config.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  spec:
    tests:
      - spec_path: source_zendesk_talk/spec.json
connector_image: airbyte/source-zendesk-talk:dev
test_strictness_level: high
