acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: profiles
          - name: sponsored_brands_ad_groups
          - name: sponsored_brands_campaigns
          - name: sponsored_brands_keywords
          - name: attribution_report_performance_creative
          - name: attribution_report_performance_adgroup
          - name: attribution_report_products
          - name: attribution_report_performance_campaign
        expect_records:
          exact_order: false
          extra_fields: false
          extra_records: false
          path: integration_tests/expected_records.txt
      - config_path: secrets/config_report.json
        timeout_seconds: 2400
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
      - config_path: secrets/config_report.json
        configured_catalog_path: integration_tests/configured_catalog_report.json
        ignored_fields:
          sponsored_products_report_stream:
            - updatedAt
        timeout_seconds: 3600
  incremental:
    tests:
      - config_path: secrets/config_report.json
        configured_catalog_path: integration_tests/configured_catalog_report.json
        cursor_paths:
          sponsored_products_report_stream:
            - "1861552880916640"
            - reportDate
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 2400
  spec:
    tests:
      - spec_path: integration_tests/spec.json
connector_image: airbyte/source-amazon-ads:dev
test_strictness_level: high
