acceptance_tests:
  basic_read:
    tests:
    - config_path: secrets/config.json
      expect_records:
        path: integration_tests/expected_records/csv.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv.jsonl
      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_custom_encoding_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_custom_encoding.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/v4_csv_custom_encoding_config.json
##      # This test fails because custom encoding isn't implemented
##      expect_records:
##        path: integration_tests/expected_records/v4_csv_custom_encoding.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_custom_format_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_custom_format.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_csv_custom_format_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv_custom_format.jsonl
      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_user_schema_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_user_schema.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_csv_user_schema_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv_user_schema.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/legacy_csv_user_schema_cast_complex_config.json
##      # This test cannot pass because the discover schema interprets the type as being an object, but the data is a string
##      expect_records:
##        path: integration_tests/expected_records/legacy_csv_user_schema_cast_complex.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/v4_csv_user_schema_cast_complex_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv_user_schema_cast_complex.jsonl
      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_no_header_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_no_header.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_csv_no_header_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv_no_header.jsonl
      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_skip_rows_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_skip_rows.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_csv_skip_rows_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv_skip_rows.jsonl
      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_skip_rows_no_header_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_skip_rows_no_header.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/v4_csv_skip_rows_no_header_config.json
##      # This test doesn't currently work because skipping rows before the header without a header is not considered valid
##      expect_records:
##        path: integration_tests/expected_records/v4_csv_skip_rows_no_header.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_with_nulls_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_with_nulls.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_csv_with_nulls_config.json
      expect_records:
        path: integration_tests/expected_records/v4_csv_with_nulls.jsonl
      timeout_seconds: 1800
    - config_path: secrets/legacy_csv_with_null_bools_config.json
      expect_records:
        path: integration_tests/expected_records/legacy_csv_with_null_bools.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/v4_csv_with_null_bools_config.json
##      # This test requires datatype inference to pass
##      # Because it needs the boolean values to be converted to null, but the strings to be kept as is
##      expect_records:
##        path: integration_tests/expected_records/v4_csv_with_null_bools.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/parquet_config.json
      expect_records:
        path: integration_tests/expected_records/parquet.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_parquet_config.json
      expect_records:
        path: integration_tests/expected_records/v4_parquet.jsonl
      timeout_seconds: 1800
    - config_path: secrets/parquet_dataset_config.json
      expect_records:
        path: integration_tests/expected_records/parquet_dataset.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_parquet_dataset_config.json
      expect_records:
        path: integration_tests/expected_records/v4_parquet_dataset.jsonl
      timeout_seconds: 1800
    - config_path: secrets/parquet_dataset_config.json
      expect_records:
        path: integration_tests/expected_records/parquet_dataset.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/legacy_parquet_decimal_config.json
      ##      # This test does not pass because the values are not converted
##      expect_records:
##        path: integration_tests/expected_records/legacy_parquet_decimal.jsonl
##      timeout_seconds: 1800
##    - config_path: secrets/v4_parquet_decimal_config.json
      ##      # This test does not pass because the values are not converted
##      expect_records:
##        path: integration_tests/expected_records/v4_parquet_decimal.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/v4_parquet_decimal_as_float_config.json
      expect_records:
        path: integration_tests/expected_records/v4_parquet_decimal_as_float.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/legacy_parquet_duration_list_struct_config.json
##      # This test fails because durations are expected to be integers
##      expect_records:
##        path: integration_tests/expected_records/legacy_parquet_duration_list_struct.jsonl
##      timeout_seconds: 1800
##    - config_path: secrets/v4_parquet_duration_list_struct_config.json
##      # This test fails because durations are expected to be integers
##      expect_records:
##        path: integration_tests/expected_records/v4_parquet_duration_list_struct.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/avro_config.json
      expect_records:
        path: integration_tests/expected_records/avro.jsonl
      timeout_seconds: 1800
    - config_path: secrets/v4_avro_config.json
      expect_records:
        path: integration_tests/expected_records/v4_avro.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/legacy_avro_duration_config.json
##      # This test fails because the parser isn't able to properly parse the file
##      expect_records:
##        path: integration_tests/expected_records/legacy_duration_avro.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/v4_avro_duration_config.json
      expect_records:
        path: integration_tests/expected_records/v4_avro_duration.jsonl
      timeout_seconds: 1800
##    - config_path: secrets/legacy_avro_decimal_config.json
##      #      # This test fails because the parser isn't able to properly parse the file
##      expect_records:
##        path: integration_tests/expected_records/legacy_avro_decimal.jsonl
##      timeout_seconds: 1800
##    - config_path: secrets/v4_avro_decimal_config.json
##      # This test fails because the decimals are not converted to strings
##      expect_records:
##        path: integration_tests/expected_records/v4_avro_decimal.jsonl
##      timeout_seconds: 1800
##    - config_path: secrets/v4_avro_decimal_as_float_config.json
##      # This test fails because the connector detects the type as a string but leaves it as a float
##      expect_records:
##        path: integration_tests/expected_records/v4_avro_decimal_as_float.jsonl
##      timeout_seconds: 1800
    - config_path: secrets/jsonl_config.json
      expect_records:
        path: integration_tests/expected_records/jsonl.jsonl
      timeout_seconds: 1800
    - config_path: secrets/jsonl_newlines_config.json
      expect_records:
        path: integration_tests/expected_records/jsonl_newlines.jsonl
      timeout_seconds: 1800
#
#  connection:
#    tests:
#    - config_path: secrets/config.json
#      status: succeed
#    - config_path: secrets/v4_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_custom_encoding_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_custom_encoding_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_custom_format_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_custom_format_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_user_schema_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_user_schema_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_user_schema_cast_complex_config.json
    # This test cannot pass
#      status: succeed
#    - config_path: secrets/v4_csv_user_schema_cast_complex_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_no_header_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_no_header_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_skip_rows_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_skip_rows_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_skip_rows_no_header_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_skip_rows_no_header_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_with_nulls_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_with_nulls_config.json
#      status: succeed
#    - config_path: secrets/legacy_csv_with_null_bools_config.json
#      status: succeed
#    - config_path: secrets/v4_csv_with_null_bools_config.json
#      status: succeed
#    - config_path: secrets/parquet_config.json
#      status: succeed
#    - config_path: secrets/avro_config.json
#      status: succeed
#    - config_path: secrets/jsonl_config.json
#      status: succeed
#    - config_path: secrets/jsonl_newlines_config.json
#      status: succeed
#    - config_path: integration_tests/invalid_config.json
#      status: failed
#  discovery:
#    tests:
#    - config_path: secrets/config.json
#    - config_path: secrets/legacy_csv_custom_encoding_config.json
#    - config_path: secrets/legacy_csv_custom_format_config.json
#    - config_path: secrets/legacy_csv_user_schema_config.json
#    - config_path: secrets/legacy_csv_no_header_config.json
#    - config_path: secrets/legacy_csv_skip_rows_config.json
#    - config_path: secrets/legacy_csv_with_nulls_config.json
#    - config_path: secrets/parquet_config.json
#    - config_path: secrets/avro_config.json
#    - config_path: secrets/jsonl_config.json
#    - config_path: secrets/jsonl_newlines_config.json
#  full_refresh:
#    tests:
#    - config_path: secrets/config.json
#      configured_catalog_path: integration_tests/configured_catalogs/csv.json
#      timeout_seconds: 1800
#    - config_path: secrets/parquet_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/parquet.json
#      timeout_seconds: 1800
#    - config_path: secrets/avro_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/avro.json
#      timeout_seconds: 1800
#    - config_path: secrets/jsonl_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
#      timeout_seconds: 1800
#    - config_path: secrets/jsonl_newlines_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
#      timeout_seconds: 1800
#
#  incremental:
#    tests:
#    - config_path: secrets/config.json
#      configured_catalog_path: integration_tests/configured_catalogs/csv.json
#      cursor_paths:
#        test:
#        - _ab_source_file_last_modified
#      future_state:
#        future_state_path: integration_tests/abnormal_state.json
#      timeout_seconds: 1800
#    - config_path: secrets/parquet_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/parquet.json
#      cursor_paths:
#        test:
#        - _ab_source_file_last_modified
#      future_state:
#        future_state_path: integration_tests/abnormal_state.json
#      timeout_seconds: 1800
#    - config_path: secrets/avro_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/avro.json
#      cursor_paths:
#        test:
#        - _ab_source_file_last_modified
#      future_state:
#        future_state_path: integration_tests/abnormal_state.json
#      timeout_seconds: 1800
#    - config_path: secrets/jsonl_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
#      cursor_paths:
#        test:
#        - _ab_source_file_last_modified
#      future_state:
#        future_state_path: integration_tests/abnormal_state.json
#      timeout_seconds: 1800
#    - config_path: secrets/jsonl_newlines_config.json
#      configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
#      cursor_paths:
#        test:
#        - _ab_source_file_last_modified
#      future_state:
#        future_state_path: integration_tests/abnormal_state.json
#      timeout_seconds: 1800
#  spec:
#    tests:
#    - spec_path: integration_tests/spec.json
connector_image: airbyte/source-s3:dev
#test_strictness_level: high
