# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-s3:dev
tests:
  spec:
    - spec_path: "integration_tests/spec.json"
  connection:
    # for CSV format
    - config_path: "secrets/config.json"
      status: "succeed"
    # for Parquet format
    - config_path: "secrets/parquet_config.json"
      status: "succeed"
    # # for Avro format
    - config_path: "secrets/avro_config.json"
      status:
        "succeed"
        # for JSON format
    - config_path: "secrets/json_config.json"
      status: "succeed"
    # for custom server
    - config_path: "integration_tests/config_minio.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    # for CSV format
    - config_path: "secrets/config.json"
    # for Parquet format
    - config_path: "secrets/parquet_config.json"
    # # for Avro format
    - config_path: "secrets/avro_config.json"
    # for JSON format
    - config_path: "secrets/jsonl_config.json"
    # for custom server
    - config_path: "integration_tests/config_minio.json"
  basic_read:
    # for CSV format
    - config_path: "secrets/config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalogs/csv.json"
      expect_records:
        path: "integration_tests/expected_records/csv.txt"
    # for Parquet format
    - config_path: "secrets/parquet_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalogs/parquet.json"
      expect_records:
        path: "integration_tests/expected_records/parquet.txt"
      # for Avro format
    - config_path: "secrets/avro_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalogs/avro.json"
      expect_records:
        path: "integration_tests/expected_records/avro.txt"
    # for JSONL format
    - config_path: "secrets/jsonl_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalogs/jsonl.json"
      expect_records:
        path: "integration_tests/expected_records/jsonl.txt"
    # for custom server
    - config_path: "integration_tests/config_minio.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/csv.json"
      # expected records contains _ab_source_file_last_modified property which
      # is modified all the time s3 file changed and for custom server it is
      # file creating date and it always new. Uncomment this line when SAT
      # would have ability to ignore specific fields from expected records.
      # expect_records:
      #  path: "integration_tests/expected_records/custom_server.txt"
  incremental:
    # for CSV format
    - config_path: "secrets/config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalog.json"
      cursor_paths:
        test: ["_ab_source_file_last_modified"]
      future_state_path: "integration_tests/abnormal_state.json"
    # for Parquet format
    - config_path: "secrets/parquet_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/parquet_configured_catalog.json"
      cursor_paths:
        test: ["_ab_source_file_last_modified"]
      future_state_path: "integration_tests/abnormal_state.json"
    # for Avro format
    - config_path: "secrets/avro_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalog.json"
      cursor_paths:
        test: ["_ab_source_file_last_modified"]
      future_state_path: "integration_tests/abnormal_state.json"
    # for JSON format
    - config_path: "secrets/json_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/json_configured_catalog.json"
      cursor_paths:
        test: ["_ab_source_file_last_modified"]
      future_state_path: "integration_tests/abnormal_state.json"
    # for custom server
    - config_path: "integration_tests/config_minio.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalog.json"
      cursor_paths:
        test: ["_ab_source_file_last_modified"]
      future_state_path: "integration_tests/abnormal_state.json"

  full_refresh:
    # for CSV format
    - config_path: "secrets/config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalog.json"
    # for Parquet format
    - config_path: "secrets/parquet_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/parquet_configured_catalog.json"
    # for Avro format
    - config_path: "secrets/avro_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalog.json"
    # for JSON format
    - config_path: "secrets/json_config.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/json_configured_catalog.json"
    # for custom server
    - config_path: "integration_tests/config_minio.json"
      timeout_seconds: 1800
      configured_catalog_path: "integration_tests/configured_catalog.json"
