acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        expect_records:
          path: integration_tests/expected_records/csv.txt
        timeout_seconds: 1800
      - config_path: secrets/parquet_config.json
        expect_records:
          path: integration_tests/expected_records/parquet.txt
        timeout_seconds: 1800
      - config_path: secrets/avro_config.json
        expect_records:
          path: integration_tests/expected_records/avro.txt
        timeout_seconds: 1800
      - config_path: secrets/jsonl_config.json
        expect_records:
          path: integration_tests/expected_records/jsonl.txt
        timeout_seconds: 1800
      - config_path: secrets/jsonl_newlines_config.json
        expect_records:
          path: integration_tests/expected_records/jsonl_newlines.txt
        timeout_seconds: 1800
      - config_path: integration_tests/config_minio.json
        timeout_seconds: 1800
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/parquet_config.json
        status: succeed
      - config_path: secrets/avro_config.json
        status: succeed
      - config_path: secrets/jsonl_config.json
        status: succeed
      - config_path: secrets/jsonl_newlines_config.json
        status: succeed
      - config_path: integration_tests/config_minio.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
      - config_path: secrets/parquet_config.json
      - config_path: secrets/avro_config.json
      - config_path: secrets/jsonl_config.json
      - config_path: secrets/jsonl_newlines_config.json
      - config_path: integration_tests/config_minio.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalogs/csv.json
        timeout_seconds: 1800
      - config_path: secrets/parquet_config.json
        configured_catalog_path: integration_tests/configured_catalogs/parquet.json
        timeout_seconds: 1800
      - config_path: secrets/avro_config.json
        configured_catalog_path: integration_tests/configured_catalogs/avro.json
        timeout_seconds: 1800
      - config_path: secrets/jsonl_config.json
        configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
        timeout_seconds: 1800
      - config_path: secrets/jsonl_newlines_config.json
        configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
        timeout_seconds: 1800
      - config_path: integration_tests/config_minio.json
        configured_catalog_path: integration_tests/configured_catalogs/csv.json
        timeout_seconds: 1800
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalogs/csv.json
        cursor_paths:
          test:
            - _ab_source_file_last_modified
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
      - config_path: secrets/parquet_config.json
        configured_catalog_path: integration_tests/configured_catalogs/parquet.json
        cursor_paths:
          test:
            - _ab_source_file_last_modified
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
      - config_path: secrets/avro_config.json
        configured_catalog_path: integration_tests/configured_catalogs/avro.json
        cursor_paths:
          test:
            - _ab_source_file_last_modified
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
      - config_path: secrets/jsonl_config.json
        configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
        cursor_paths:
          test:
            - _ab_source_file_last_modified
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
      - config_path: secrets/jsonl_newlines_config.json
        configured_catalog_path: integration_tests/configured_catalogs/jsonl.json
        cursor_paths:
          test:
            - _ab_source_file_last_modified
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
      - config_path: integration_tests/config_minio.json
        configured_catalog_path: integration_tests/configured_catalogs/csv.json
        cursor_paths:
          test:
            - _ab_source_file_last_modified
        future_state:
          future_state_path: integration_tests/abnormal_state.json
        timeout_seconds: 1800
  spec:
    tests:
      - spec_path: integration_tests/spec.json
connector_image: airbyte/source-s3:dev
test_strictness_level: high
