[tool.poetry]
name = "source-s3"
version = "0.1.0"
description = "Source implementation for S3"
authors = ["Airbyte"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

# Comment or uncomment to toggle between pinned versions vs local/latest code in the branch
# After toggling the dependency, you must rerun `poetry lock && poetry install` 
airbyte-cdk = "^0.51.8"
# airbyte-cdk = { path = "../../../airbyte-cdk/python", develop = true }

# Other 
dill = "0.3.4"
fastavro = "1.4.11"
pyarrow = "12.0.1"
python-snappy = "0.6.1"
pytz = "2023.3"
smart-open = {extras = ["s3"], version = "5.1.0"}
wcmatch = "8.4.0"

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.11.0"
pytest-mock = "^3.11.1"
pytest = "^7.4.0"
pandas = "^2.0.3"
psutil = "^5.9.5"
pytest-order = "^1.1.0"
netifaces = "^0.11.0"
docker = "^6.1.3"
avro = "^1.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
