connector_image: airbyte/source-sendgrid:dev
tests:
  spec:
    - spec_path: "source_sendgrid/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "sample_files/new_configured_catalog.json"
      expect_records:
        path: "integration_tests/generated_expected_records.txt"
        extra_fields: yes
        exact_order: yes
        extra_records: no
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "sample_files/new_configured_catalog.json"
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "sample_files/no_spam_reports_configured_catalog.json"
      future_state_path: "sample_files/abnormal_state.json"
      cursor_paths:
        bounces: ["created"]
