connector_image: airbyte/source-sendgrid:dev
tests:
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "sample_files/new_configured_catalog.json"
      expect_records:
        path: "integration_tests/generated_expected_records.txt"
        extra_fields: no
        exact_order: no
        extra_records: no
