connector_image: airbyte/source-github:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_github/spec.json"
  connection:
    - config_path: "secrets/test_config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/test_config.json"
  basic_read:
    - config_path: "secrets/test_config.json"
      configured_catalog_path: "integration_tests/test_catalog.json"
      empty_streams: ["commit_comment_reactions"]

  full_refresh:
    - config_path: "secrets/test_config.json"
      configured_catalog_path: "integration_tests/test_catalog.json"
