acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        ignored_fields:
          user_insights:
            - email_contacts
            - follower_count
            - get_directions_clicks
            - impressions
            - phone_call_clicks
            - profile_views
            - reach
            - text_message_clicks
            - website_clicks
            - impressions_week
            - reach_week
            - impressions_days_28
            - reach_days_28
            - online_followers
  spec:
    tests:
      - spec_path: integration_tests/spec.json
connector_image: airbyte/source-instagram:dev
test_strictness_level: high
