acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/config.json
        empty_streams:
          - name: transactions
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
      - config_path: secrets/config_oauth.json
        status: succeed
      - config_path: integration_tests/invalid_config_oauth.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  spec:
    tests:
      - spec_path: source_paypal_transaction/spec.json
connector_image: airbyte/source-paypal-transaction:dev
test_strictness_level: high
