name: "Github Labeler Issues Edition"
on: push
# UNCOMMENT ME
#  issues:
#    types: [opened, labeled, unlabeled]

jobs:
  find_valid_pat:
    name: "Find a PAT with room for actions"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      pat: ${{ steps.variables.outputs.pat }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Check PAT rate limits
        id: variables
        run: |
          ./tools/bin/find_non_rate_limited_PAT \
            ${{ secrets.OCTAVIA_PAT }} \
            ${{ secrets.AIRBYTEIO_PAT }} \
            ${{ secrets.OSS_BUILD_RUNNER_GITHUB_PAT }} \
            ${{ secrets.SUPERTOPHER_PAT }} \
            ${{ secrets.DAVINCHIA_PAT }}

  shared-pulls:
    name: "Label github issues for tracking"
    needs: find_valid_pat
    runs-on: ubuntu-latest
    steps:
      - uses: nick-fields/private-action-loader@v3
        with:
          pal-repo-token: ${{ needs.find_valid_pat.outputs.pat }}
          pal-repo-name: airbytehq/workflow-actions@production
          # the following input gets passed to the private action
          # warning in the GH action for these inputs is expected
          token: ${{ secrets.OCTAVIA_PAT }}
          command: "issue"
