name: "Github Labeler Issues Edition"
on:
  branch: toph_adds_PAT_rotation_to_GH_issues_part2
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  shared-issues:
    name: "Adds github labels for shared issues"
    runs-on: ubuntu-latest
    steps:
      - uses: nick-fields/private-action-loader@v3
        with:
          pal-repo-token: "${{ secrets.OCTAVIA_PAT }}"
          pal-repo-name: airbytehq/workflow-actions@production
          # the following input gets passed to the private action
          token: "${{ secrets.OCTAVIA_PAT }}"
          command: "issue"
