name: "Java CDK CI"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - '.github/workflows/java_cdk.yml'
      - 'airbyte-ci/java-cdk/**'
      - 'airbyte-cdk/java/**'
  workflow_dispatch:
jobs:
  java_cdk_ci:
    name: Java CDK CI
    timeout-minutes: 60
    runs-on: conn-prod-xlarge-runner
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.gitref }}
      #TODO: Use python baked into the runner, currently this is on 3.8.10
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Run Dagger
        run: |
          export _EXPERIMENTAL_DAGGER_CLOUD_TOKEN="p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICJlNjk3YzZiYy0yMDhiLTRlMTktODBjZC0yNjIyNGI3ZDBjMDEifQ.hT6eMOYt3KZgNoVGNYI3_v4CC-s19z8uQsBkGrBhU3k"
          export _EXPERIMENTAL_DAGGER_RUNNER_HOST="unix:///var/run/buildkit/buildkitd.sock"
          export PREFECT_API_URL=""
          DAGGER_CLI_COMMIT="6ed6264f1c4efbf84d310a104b57ef1bc57d57b0"
          DAGGER_TMP_BINDIR="/tmp/dagger_${DAGGER_CLI_COMMIT}"
          export _EXPERIMENTAL_DAGGER_CLI_BIN="$DAGGER_TMP_BINDIR/dagger"
          if [ ! -f  "$_EXPERIMENTAL_DAGGER_CLI_BIN" ]; then
            mkdir -p "$DAGGER_TMP_BINDIR"
            curl "https://dl.dagger.io/dagger/main/${DAGGER_CLI_COMMIT}/dagger_${DAGGER_CLI_COMMIT}_$(uname -s | tr A-Z a-z)_$(uname -m | sed s/x86_64/amd64/).tar.gz" | tar xvz -C "$DAGGER_TMP_BINDIR"
          fi
          cd airbyte-ci/java-cdk
          poetry install
          poetry run aircmd plugin install cdk --local .
          poetry run aircmd cdk java ci --scan