name: Release hotfix version of helm charts(TBD)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      partToBump:
        required: true
        description: "Part of version to bump (major|minor|patch)"
        default: "patch"

jobs:
  # In case of self-hosted EC2 errors, remove this block.
  start-release-airbyte-runner:
    name: "Release Airbyte: Start EC2 Runner"
    needs: find_valid_pat
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Start AWS Runner
        id: start-ec2-runner
        uses: ./.github/actions/start-aws-runner
        with:
          aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ needs.find_valid_pat.outputs.pat }}

  releaseAirbyte:
    name: "Release helm charts"
    # In case of self-hosted EC2 errors, removed the `needs` line and switch back to running on ubuntu-latest.
    needs: start-release-airbyte-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-release-airbyte-runner.outputs.label }} # run the job on the newly created runner
    environment: more-secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/checkout@v3
        with:
          repository: "airbytehq/helm-charts"
          token: ${{ secrets.OCTAVIA_PAT }}
          path: "./.github/helm-charts"

      - uses: actions/setup-java@v1
        with:
          java-version: "17"

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
      # necessary to install pip
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Generate new version number
        shell: bash
        id: new_version
        env:
          PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
        run: |
          ./tools/bin/bump_version.sh

      - name: Release helm charts
        uses: ./.github/actions/publish-helm-charts
        with:
          new_version_number: ${{ steps.new_version.outputs.NEW_VERSION }}

