name: Publish connectors on merge to master

on:
  workflow_dispatch:
    inputs:
      connectors-options:
        description: "Options to pass to the 'airbyte-ci connectors' command group"
        default: "--name=source-postgres --name=source-mysql --name=source-mssql --name=source-postgres-strict-encrypt --name=source-mysql-strict-encrypt --name=source-mssql-strict-encrypt"
      publish-options:
        description: "Options to pass to the 'airbyte-ci connectors publish' command"
        default: "--pre-release"
jobs:
  publish_connectors:
    name: Publish connectors
    runs-on: dev-large-runner
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.STATUS_API_AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: "us-east-2"
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STATUS_API_AWS_SECRET_ACCESS_KEY }}
      CI_GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      GCP_GSM_CREDENTIALS: ${{ secrets.GCP_GSM_CREDENTIALS }}
      GCS_CREDENTIALS: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
      METADATA_SERVICE_GCS_CREDENTIALS: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
      METADATA_SERVICE_BUCKET_NAME: prod-airbyte-cloud-connector-metadata-service
      SPEC_CACHE_BUCKET_NAME: io-airbyte-cloud-spec-cache
      SPEC_CACHE_GCS_CREDENTIALS: ${{ secrets.SPEC_CACHE_SERVICE_ACCOUNT_KEY_PUBLISH }}
      TEST_REPORTS_BUCKET_NAME: "airbyte-connector-build-status"
      SLACK_WEBHOOK: ${{ secrets.PUBLISH_ON_MERGE_SLACK_WEBHOOK }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}"
      - name: Publish connectors [manual]
        id: publish-connectors
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/run-dagger-pipeline
        with:
          subcommand: "connectors ${{ github.event.inputs.connectors-options }} publish ${{ github.event.inputs.publish-options }}"
          context: "manual"
          github-token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
