name: Release Open Source Airbyte
concurrency: release-airbyte

on:
  workflow_dispatch:
    inputs:
      partToBump:
        description: "Please choose the type of version upgrade : major|minor|patch"
        required: true
        default: "patch"

env:
  PIP_ROOT_USER_ACTION: ignore

jobs:
    auto-commit-version-bump:
     runs-on: ubuntu-latest
     steps:

      - name: Checkout github-workflow-test-repo-base
        uses: actions/checkout@v3
        with:
          repository: airbytehq/github-workflow-test-repo-base
          ref: master
          path: github-workflow-test-repo-base
          fetch-depth: 0
          token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}

      - name: version bump
        id: bump_version
        working-directory: github-workflow-test-repo-base
        env:
          PART_TO_BUMP: patch
        run: ./bump_version.sh

      - name: Ensure no file change
        if: false # disable
        working-directory: github-workflow-test-repo-base
        run: git --no-pager diff && test -z "$(git --no-pager diff)"

      - name: Auto Commit Version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: github-workflow-test-repo-base
          commit_message: Bump Airbyte version from ${{ steps.bump_version.outputs.PREV_VERSION }} to ${{ steps.bump_version.outputs.NEW_VERSION }}
